const dividerData = [
  "Potresti considerarlo stupido, ma anche queste foto con te hanno contribuito a migliorarmi la vita.",
  "Rappresentano i ricordi che siamo stati in gradi di creare assieme e non potrei mai liberarmene",
  "Ogni singola foto ha un qualcosa di unico e mi ricorda qualcosa, sono così felice di poterle rivedere ogni giorno pensando a te.",
  "I nostri ricordi più belli, catturati in istanti.",
  "Ogni sorriso, ogni abbraccio, ogni momento condiviso.",
  "Un viaggio attraverso quei ricordi che ci hanno reso quel che siamo, quei ricordi che pian piano ci han fatto innamorare sempre di più amore mio.",
  "E nonostante tutto, non ci saranno mai abbastanza foto.",
  "Momenti indimenticabili catturati in fotografie, alcune più belle di altre. Ma sai cosa le rende bellissime?",
  "Che sono nostre, solo nostre e la storia che c'è dietro è la migliore mai scritta finora.",
  "Voglio scattare altre millemiliardi di foto con te e tornare a vederti sorridere, perchè tu..",
  "..Tu sei la mia felicità, Alessandra",
  "Vorrei ringraziarti per tutto questo, non pensavo mai sarei riuscito ad amare qualcuno come amo te, e quindi...",
  "...Dato che ogni foto è una pagina del nostro libro ancora incompleto, dobbiamo finire di scriverlo, non credi?.",
  "E le prime non si scordano mai",
  "Abbiamo fatto così tante foto, stupide e serie e in ognuna di queste non faccio che pensare a quanto sono contento che sia te quella con me",
  "Ogni immagine è un capitolo della nostra storia e ne abbiamo ancora tanti da scrivere.",
  "Momenti preziosi che mi hanno cambiato la vita.",
  "Momenti preziosi che ci hanno cambiato la vita.",
];
